apiVersion: v1
kind: Service
metadata:
  name: my-app-balancer
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 8000 # The port to expose to the outside
      targetPort: 8080 # The port the application is running on in the pods
  type: LoadBalancer
  sessionAffinity: ClientIP
